### ISSUE TITLE
Problem in scrolling , when increas cell height 540

### ISSUE THREAD

**Issue by ShardaPrasad** [Yalantis/PullToRefresh#108] opened 2018-10-26 07:19 UTC
Hi,
Its good library for pull to refresh but i am facing problem, when i increase cell size 540. That condition .bottom scroll automatic scroll approx. 10 or 11 index.

**Comment by sergey-prikhodko** [comment] 2020-04-03 10:11
Hi @ShardaPrasad , sorry for the late reply.
I tested this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue

**Closed as completed by sergey-prikhodko** 2020-04-03 10:11 UTC
Labels: type: bug, priority: low, status: queued
