### ISSUE TITLE
scrollView.contentOffset Error

### ISSUE THREAD

**Issue by zhjch80** [Yalantis/PullToRefresh#101] opened 2018-08-21 06:03 UTC
The pull up loads more，scrollView.contentOffset error. The expectation should be UIEdgeInsets(top: 0.0, left: 0.0, bottom: 0.0, right: 0.0), However, is UIEdgeInsets(top: 64.0, left: 0.0, bottom: 0.0, right: 0.0).

**Comment by zhjch80** [comment] 2018-08-21 08:07
at: PullToRefresh.swift line:95

**Comment by zhjch80** [comment] 2018-08-21 08:11
at: PullToRefresh.swift line:95

temporary solution:
                    scrollView?.contentInset = UIEdgeInsets(top: 0, left: self.scrollViewDefaultInsets.left, bottom: self.scrollViewDefaultInsets.bottom, right: self.scrollViewDefaultInsets.right)
//                    scrollView?.contentInset = self.scrollViewDefaultInsets

please consult the author,how can I better solve this problem？thank you.

**Comment by leisiyu** [comment] 2019-01-30 02:05
got the same problem.

**Comment by sergey-prikhodko** [comment] 2020-04-02 18:32
Hi @zhjch80 @leisiyu , sorry for the late reply.
I reviewed this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue

**Closed as completed by sergey-prikhodko** 2020-04-02 18:32 UTC
Labels: type: bug, priority: medium, status: invalid
