### ISSUE TITLE
Sometime Activity Indicator is small

### ISSUE THREAD

**Issue by windyit08** [Yalantis/PullToRefresh#49] opened 2016-11-22 10:17 UTC
Sorry my English is not good, please see screen record video for more detail

https://www.dropbox.com/s/3vcg4c1k1u9pxnk/PullToRefreshDemo_Bug_Report.mov?dl=0

### Environment

- Swift version: 3
- iOS version: 10.1
- Device: Simulator iPhone 6
- Xcode version: 8.1

### Project that demonstrates the bug

PullToRefreshDemo (branch: develop --- Latest commit 3deb872  26 days ago @serejahh serejahh Bump version)

**Comment by sergey-prikhodko** [comment] 2020-04-03 11:10
Hi @windyit08 , sorry for the late reply.
I tested this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue

**Closed as completed by sergey-prikhodko** 2020-04-03 11:10 UTC
Labels: type: bug, priority: low, status: queued
