### ISSUE TITLE
[Bug]The tableView appear that contentOffset  bigger

### ISSUE THREAD

**Issue by Syhpox** [Yalantis/PullToRefresh#61] opened 2017-04-07 09:51 UTC
# Report
## Report a bug
first,run your demo,when the top refresh is working, immediately let the bottom refresh works and wait for the finished of the two refresh,you find that everytime one such operation, contentOffset become twice as large as

### Environment

- Version of the component: 2.0.2
- Swift version: 3.0
- iOS version: 10.3
- Device: 6s plus
- Xcode version: 8.3

### Project that demonstrates the bug
it is  your demo

**Comment by Syhpox** [comment] 2017-04-10 02:05
everytime one such operation, contentOffset become twice as large as

**Comment by sergey-prikhodko** [comment] 2020-04-03 08:15
Hello @Syhpox , sorry for the late reply.
I reviewed this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue

**Closed as completed by sergey-prikhodko** 2020-04-03 08:15 UTC
Labels: type: bug, priority: low, status: queued
