### ISSUE TITLE
Section header displaced

### ISSUE THREAD

**Issue by bonyadmitr** [Yalantis/PullToRefresh#63] opened 2017-04-15 21:50 UTC
# Report

![screen shot 2017-04-16 at 00 37 34](https://cloud.githubusercontent.com/assets/24361363/25066975/205c1fca-223e-11e7-90c4-4384d0443cd9.png)

###  What did you do?

Pull to refresh + some scroll

### What did you expect to happen?

Normal sticky section header

### What happened instead?

Section header displaced.
See screenshot.

### Your Environment

- Version of the component: ~> 2.0
- Swift version: 3
- iOS version: 9.3.5
- Device: simulator 4s, 5
- Xcode version: 8.3

### Project that demonstrates the bug

```swift
import UIKit
import PullToRefresh

class YalantisController: UIViewController {
    
    @IBOutlet weak var tableView: UITableView!
    let dataSource = TableDataSource()
    let refresher = PullToRefresh()
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        dataSource.tableView = tableView
        tableView.addPullToRefresh(refresher) {
            DispatchQueue.main.asyncAfter(deadline: .now() + 3) {
                print("refreshData")
                self.dataSource.someArray = self.dataSource.someArray.reversed()
                self.tableView.endRefreshing(at: .top)
            }
        }
    }
    
    deinit {
        tableView.removePullToRefresh(tableView.topPullToRefresh!)
        print(self.classForCoder)
    }
}


import UIKit

class TableDataSource: NSObject {
    
    @IBOutlet weak var tableView: UITableView! {
        didSet { tableView.dataSource = self }
    }
    
    var someArray: [Int] = [1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1, 2, 3, 4, 5, 6, 1] {
        didSet { tableView.reloadData() }
    }
}
extension TableDataSource: UITableViewDataSource {
    func numberOfSections(in tableView: UITableView) -> Int {
        return 4
    }
    
    func tableView(_ tableView: UITableView, numberOfRowsInSection section: Int) -> Int {
        return someArray.count
    }
    
    func tableView(_ tableView: UITableView, cellForRowAt indexPath: IndexPath) -> UITableViewCell {
        let cell = tableView.dequeueReusableCell(withIdentifier: "cell", for: indexPath)
        cell.textLabel?.text = String(someArray[indexPath.row])
        return cell
    }
    
    func tableView(_ tableView: UITableView, titleForHeaderInSection section: Int) -> String? {
        return "Section \(section + 1)"
    }
}
```

**Comment by thereal1** [comment] 2017-05-22 11:02
I'm having the same sort of problem

**Comment by nickdnk** [comment] 2017-09-24 19:25
Yo, guys, this is totally broken on iOS 11 and XC9. We need someone to take a look at this. Help!

**Comment by sergey-prikhodko** [comment] 2020-04-02 17:59
Hello @bonyadmitr ,sorry for the late reply. 
I reviewed this issue, looks like it was fixed in new versions.
If you can reproduce this again, you can open a new issue

**Closed as completed by sergey-prikhodko** 2020-04-02 17:59 UTC
Labels: type: bug, priority: medium, status: work in progress
